version: '3.8'

services:
    dev:
        image: vsc-fastify-mongoose-plugin
        build:
            context: ../
            dockerfile: docker/dev/Dockerfile
            args:
                - IDIR=fastify-mongoose-plugin
                #- BMODE=production # default development on Dockerfile
